### ISSUE TITLE
"This version of ChromeDriver only supports Chrome version 99"

### ISSUE THREAD

**Issue by TEBandCo** [cubicbyte/reddit-account-generator#12] opened 2023-10-21 13:26 UTC
I get the following error when tying to use the new Chrome version:
```
Message: session not created: This version of ChromeDriver only supports Chrome version 99
Current browser version is 118.0.5993.89 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00D19943+2595139]
        Ordinal0 [0x00CAC9F1+2148849]
        Ordinal0 [0x00BA4528+1066280]
        Ordinal0 [0x00BC42C3+1196739]
        Ordinal0 [0x00BBFE37+1179191]
        Ordinal0 [0x00BBD6F1+1169137]
        Ordinal0 [0x00BF0530+1377584]
        Ordinal0 [0x00BF018A+1376650]
        Ordinal0 [0x00BEB806+1357830]
        Ordinal0 [0x00BC6086+1204358]
        Ordinal0 [0x00BC6F96+1208214]
        GetHandleVerifier [0x00EBB232+1658114]
        GetHandleVerifier [0x00F7312C+2411516]
        GetHandleVerifier [0x00DAF261+560433]
        GetHandleVerifier [0x00DAE366+556598]
        Ordinal0 [0x00CB286B+2173035]
        Ordinal0 [0x00CB75F8+2192888]
        Ordinal0 [0x00CB76E5+2193125]
        Ordinal0 [0x00CC11FC+2232828]
        BaseThreadInitThunk [0x75D6FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77867C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77867C3E+238]
```

**Comment by cubicbyte** [comment] 2023-10-21 13:40
I think there is no driver for your version of chrome. Updating webdriver-manager might solve this issue, try to run:
`pip install webdriver-manager~=4.0.1`

UPD: I've just tried the fix it, please update the repo via `git pull`

**Comment by TEBandCo** [comment] 2023-10-21 14:21
> I think there is no driver for your version of chrome. Updating webdriver-manager might solve this issue, try to run:
> 
> `pip install webdriver-manager~=4.0.1`
> 
> 
> 
> UPD: I've just tried the fix it, please update the repo via `git pull`

Ace, thanks - I'll test a little later and double check the versions!

**Comment by TEBandCo** [comment] 2023-10-22 16:23
That now launches Chrome, gets to the captcha and fails, which isn't an issue, but presents the following error:
```
Message: stale element reference: stale element not found
  (Session info: chrome=118.0.5993.89)
Stacktrace:
        GetHandleVerifier [0x00BC4DE3+43907]
        (No symbol) [0x00B50741]
        (No symbol) [0x00A433ED]
        (No symbol) [0x00A4D6B1]
        (No symbol) [0x00A476F6]
        (No symbol) [0x00A46408]
        (No symbol) [0x00A4879A]
        (No symbol) [0x00A487D7]
        (No symbol) [0x00A48840]
        (No symbol) [0x00A781FB]
        (No symbol) [0x00AA66D0]
        (No symbol) [0x00A92B5C]
        (No symbol) [0x00AA55CA]
        (No symbol) [0x00A92956]
        (No symbol) [0x00A6E17E]
        (No symbol) [0x00A6F32D]
        GetHandleVerifier [0x00E75AF9+2865305]
        GetHandleVerifier [0x00EBE78B+3163435]
        GetHandleVerifier [0x00EB8441+3138017]
        GetHandleVerifier [0x00C4E0F0+605840]
        (No symbol) [0x00B5A64C]
        (No symbol) [0x00B56638]
        (No symbol) [0x00B5675F]
        (No symbol) [0x00B48DB7]
        BaseThreadInitThunk [0x75D6FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77867C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77867C3E+238]

2023-10-22 17:21:40 ERROR An error occurred during account creation. Trying again 8 more times...
```

**Comment by TEBandCo** [comment] 2023-10-22 16:33
> That now launches Chrome, gets to the captcha and fails, which isn't an issue, but presents the following error:
> 
> ```
> Message: stale element reference: stale element not found
>   (Session info: chrome=118.0.5993.89)
> Stacktrace:
>         GetHandleVerifier [0x00BC4DE3+43907]
>         (No symbol) [0x00B50741]
>         (No symbol) [0x00A433ED]
>         (No symbol) [0x00A4D6B1]
>         (No symbol) [0x00A476F6]
>         (No symbol) [0x00A46408]
>         (No symbol) [0x00A4879A]
>         (No symbol) [0x00A487D7]
>         (No symbol) [0x00A48840]
>         (No symbol) [0x00A781FB]
>         (No symbol) [0x00AA66D0]
>         (No symbol) [0x00A92B5C]
>         (No symbol) [0x00AA55CA]
>         (No symbol) [0x00A92956]
>         (No symbol) [0x00A6E17E]
>         (No symbol) [0x00A6F32D]
>         GetHandleVerifier [0x00E75AF9+2865305]
>         GetHandleVerifier [0x00EBE78B+3163435]
>         GetHandleVerifier [0x00EB8441+3138017]
>         GetHandleVerifier [0x00C4E0F0+605840]
>         (No symbol) [0x00B5A64C]
>         (No symbol) [0x00B56638]
>         (No symbol) [0x00B5675F]
>         (No symbol) [0x00B48DB7]
>         BaseThreadInitThunk [0x75D6FCC9+25]
>         RtlGetAppContainerNamedObjectPath [0x77867C6E+286]
>         RtlGetAppContainerNamedObjectPath [0x77867C3E+238]
> 
> 2023-10-22 17:21:40 ERROR An error occurred during account creation. Trying again 8 more times...
> ```

Update: I've since ran the script again, and it now seems to be working well even when failing captcha - maybe was a one time issue.

**Comment by cubicbyte** [comment] 2023-10-22 18:03
Happy to see that problem has been solved!

About the captcha error, I've never seen it, but if I manage to reproduce it, I'll fix it. But since this error isn't related to the current issue, I'm closing it.

**Closed by cubicbyte** 2023-10-22 18:03 UTC
